/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.forms.masterfile.companyViews;
import controllers.CompanyController;
import dbconnection.DatabaseConnection;
import java.awt.HeadlessException;
import java.lang.reflect.Array;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import models.Company;
import designTable.company.CompanyListTbl;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.FocusManager;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JTable;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author chris
 */
public class CompanyDetailForm extends javax.swing.JInternalFrame {

    static Connection conn = DatabaseConnection.getConnection();
    /**
     * Creates new form CompanyDetailForm
     */
    public CompanyDetailForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanelDetail = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNew1 = new javax.swing.JButton();
        controlFormPanel = new javax.swing.JPanel();
        txtCompany = new javax.swing.JTextField();
        txtBusinessStyle = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        txtClassification = new javax.swing.JTextField();
        lblCompany = new javax.swing.JLabel();
        lblClassificatio = new javax.swing.JLabel();
        lblBusinessStyle = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblContactNo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Company Detail");
        setMinimumSize(new java.awt.Dimension(800, 458));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        controlPanelDetail.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNew1.setText("New");
        btnNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNew1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelDetailLayout = new javax.swing.GroupLayout(controlPanelDetail);
        controlPanelDetail.setLayout(controlPanelDetailLayout);
        controlPanelDetailLayout.setHorizontalGroup(
            controlPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew1)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        controlPanelDetailLayout.setVerticalGroup(
            controlPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelDetailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnEdit)
                    .addComponent(btnCancel)
                    .addComponent(btnDelete)
                    .addComponent(btnNew1))
                .addContainerGap())
        );

        lblCompany.setText("Company Name:");

        lblClassificatio.setText("Classification:");

        lblBusinessStyle.setText("Business Style:");

        lblAddress.setText("Address:");

        lblContactNo.setText("Contact No.:");

        jLabel1.setText("Company ID # :");

        txtId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout controlFormPanelLayout = new javax.swing.GroupLayout(controlFormPanel);
        controlFormPanel.setLayout(controlFormPanelLayout);
        controlFormPanelLayout.setHorizontalGroup(
            controlFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlFormPanelLayout.createSequentialGroup()
                        .addGroup(controlFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCompany)
                            .addGroup(controlFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtBusinessStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtClassification, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClassificatio)
                            .addComponent(lblBusinessStyle))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(controlFormPanelLayout.createSequentialGroup()
                        .addGroup(controlFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddress)
                            .addComponent(lblContactNo)
                            .addGroup(controlFormPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        controlFormPanelLayout.setVerticalGroup(
            controlFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                .addComponent(lblCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBusinessStyle)
                .addGap(1, 1, 1)
                .addComponent(txtBusinessStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClassificatio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassification, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblAddress)
                .addGap(3, 3, 3)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContactNo)
                .addGap(1, 1, 1)
                .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controlFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(controlPanelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(controlPanelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
            try {
            CompanyController contrler = new CompanyController();
            Company _company = new Company();
            _company.setCompanyName(txtCompany.getText());
            _company.setBusinessStyle(txtBusinessStyle.getText());
            _company.setClassification(txtClassification.getText());
            _company.setAddress(txtAddress.getText());
            _company.setContactNo(txtContactNo.getText());
            contrler.save(_company);
            JOptionPane.showMessageDialog(null, txtCompany.getText() + " " +"is successfully saved!");
            clear();             
            txtCompany.requestFocus();
            testFunction();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, txtCompany.getText() + " " +"is not added to the record");
           
        }
       isXClicked = true;
    }//GEN-LAST:event_btnSaveActionPerformed
   
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        CompanyListForm _companyList = new CompanyListForm();
        int tempId = CompanyListForm.arryIdHolder[0];
        
        if (_companyList.isAddButtonClick == false){
            CompanyController cntrler = new CompanyController();
            String[] tempArry = new String[6];
    
                try {
                  for(int i = 0; i < tempArry.length;i++){
                    tempArry[i] = Array.get(cntrler.getCompanyById(tempId), i).toString();
                    }

                } catch (Exception e) { }
                txtId.setText(tempArry[0]);
                txtCompany.setText(tempArry[1]);
                txtBusinessStyle.setText(tempArry[2]);
                txtClassification.setText(tempArry[3]);
                txtAddress.setText(tempArry[4]);
                txtContactNo.setText(tempArry[5]);
                viewOnly();
        }
        else {
        readyToEdit();
        txtCompany.requestFocus();
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNew1ActionPerformed
        clear();
        readyToEdit();
        txtCompany.requestFocus();
    }//GEN-LAST:event_btnNew1ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        readyToEdit();
        txtCompany.requestFocus();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            CompanyController controler = new CompanyController();
            Company _company = new Company();
            _company.setCompanyName(txtCompany.getText());
            _company.setBusinessStyle(txtBusinessStyle.getText());
            _company.setClassification(txtClassification.getText());
            _company.setAddress(txtAddress.getText());
            _company.setContactNo(txtContactNo.getText());
            _company.setId(Integer.valueOf(txtId.getText()));
            controler.UpdateCompany(_company);
            JOptionPane.showMessageDialog(null, txtCompany.getText() + " " +"is successfully saved!");
            viewOnly();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, txtCompany.getText() + " " +"is not updated!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            CompanyController controler = new CompanyController();
            controler.remove(Integer.valueOf(txtId.getText()));
            JOptionPane.showMessageDialog(null, "The record " +"is successfully removed!");
            clear();
            txtCompany.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "The record " +"is not removed!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void clear(){
    txtId.setText("");
    txtCompany.setText("");
    txtBusinessStyle.setText("");
    txtClassification.setText("");
    txtAddress.setText("");
    txtContactNo.setText("");
    }
    public void viewOnly(){
    txtCompany.setEditable(false);
    txtBusinessStyle.setEditable(false);
    txtClassification.setEditable(false);
    txtAddress.setEditable(false);
    txtContactNo.setEditable(false);
    }
    public void readyToEdit(){
    txtCompany.setEditable(true);
    txtBusinessStyle.setEditable(true);
    txtClassification.setEditable(true);
    txtAddress.setEditable(true);
    txtContactNo.setEditable(true);
    }

   
    public void testFunction()
    {
       
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew1;
    public javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel controlFormPanel;
    private javax.swing.JPanel controlPanelDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBusinessStyle;
    private javax.swing.JLabel lblClassificatio;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblContactNo;
    public javax.swing.JTextField txtAddress;
    public javax.swing.JTextField txtBusinessStyle;
    public javax.swing.JTextField txtClassification;
    public javax.swing.JTextField txtCompany;
    public javax.swing.JTextField txtContactNo;
    private javax.swing.JLabel txtId;
    // End of variables declaration//GEN-END:variables

   public static boolean isXClicked;

    private static class FocusManagerImpl extends FocusManager {

        public FocusManagerImpl() {
        }
    }
}
